/**
 * Copyright 2024 GTN Technologies (Pvt) Ltd. All rights reserved.
 *
 * Unauthorized access, copying, publishing, sharing, reuse of algorithms,
 * concepts, design patterns and code level demonstrations are strictly prohibited
 * without any written approval of GTN Technologies (Pvt) Ltd.
 */

export const MOCK_MENA = [
	{
		exchange: 'DFM1',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'AED',
		session: 'Regular',
		buyOrderValueQty: 'Value',
		brokerCommissionBps: 1,
		minFeePerTrade: 10,
		safeCustodyFees: 10,
		fixedAmountPerTrade: 10,
		transactionFeeBps: 2,
		vatBps: 2,
		stampDutyBps: 1,
		ibCommissionBps: 1,
		settlementFeePerIsin: 1,
		fractionalSupported: 0
	},
	{
		exchange: 'DFM2',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'AED',
		session: 'Regular',
		buyOrderValueQty: 'Value',
		brokerCommissionBps: 1,
		minFeePerTrade: 10,
		safeCustodyFees: 10,
		fixedAmountPerTrade: 10,
		transactionFeeBps: 2,
		vatBps: 2,
		stampDutyBps: 1,
		ibCommissionBps: 1,
		settlementFeePerIsin: 1,
		fractionalSupported: 0
	},
	{
		exchange: 'DFM3',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'AED',
		session: 'Regular',
		buyOrderValueQty: 'Value',
		brokerCommissionBps: 1,
		minFeePerTrade: 10,
		safeCustodyFees: 10,
		fixedAmountPerTrade: 10,
		transactionFeeBps: 2,
		vatBps: 2,
		stampDutyBps: 1,
		ibCommissionBps: 1,
		settlementFeePerIsin: 1,
		fractionalSupported: 0
	},
	{
		exchange: 'DFM4',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'AED',
		session: 'Regular',
		buyOrderValueQty: 'Value',
		brokerCommissionBps: 1,
		minFeePerTrade: 10,
		safeCustodyFees: 10,
		fixedAmountPerTrade: 10,
		transactionFeeBps: 2,
		vatBps: 2,
		stampDutyBps: 1,
		ibCommissionBps: 1,
		settlementFeePerIsin: 1,
		fractionalSupported: 0
	},
	{
		exchange: 'ADSM1',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'AED',
		session: 'Regular',
		buyOrderValueQty: 'Value',
		brokerCommissionBps: 1,
		minFeePerTrade: 10,
		safeCustodyFees: 10,
		fixedAmountPerTrade: 10,
		transactionFeeBps: 2,
		vatBps: 2,
		stampDutyBps: 1,
		ibCommissionBps: 1,
		settlementFeePerIsin: 1,
		fractionalSupported: 0
	},
	{
		exchange: 'ADSM2',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'AED',
		session: 'Regular',
		buyOrderValueQty: 'Value',
		brokerCommissionBps: 1,
		minFeePerTrade: 10,
		safeCustodyFees: 10,
		fixedAmountPerTrade: 10,
		transactionFeeBps: 2,
		vatBps: 2,
		stampDutyBps: 1,
		ibCommissionBps: 1,
		settlementFeePerIsin: 1,
		fractionalSupported: 0
	},
	{
		exchange: 'ADSM3',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'AED',
		session: 'Regular',
		buyOrderValueQty: 'Value',
		brokerCommissionBps: 1,
		minFeePerTrade: 10,
		safeCustodyFees: 10,
		fixedAmountPerTrade: 10,
		transactionFeeBps: 2,
		vatBps: 2,
		stampDutyBps: 1,
		ibCommissionBps: 1,
		settlementFeePerIsin: 1,
		fractionalSupported: 0
	},
	{
		exchange: 'ADSM4',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'AED',
		session: 'Regular',
		buyOrderValueQty: 'Value',
		brokerCommissionBps: 1,
		minFeePerTrade: 10,
		safeCustodyFees: 10,
		fixedAmountPerTrade: 10,
		transactionFeeBps: 2,
		vatBps: 2,
		stampDutyBps: 1,
		ibCommissionBps: 1,
		settlementFeePerIsin: 1,
		fractionalSupported: 0
	}
];

export const MOCK_ASIA = [
	{
		exchange: 'KSE',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'AED',
		session: 'Regular',
		buyOrderValueQty: 'Quantity',
		brokerCommissionBps: 1,
		minFeePerTrade: 10,
		safeCustodyFees: 10,
		fixedAmountPerTrade: 10,
		transactionFeeBps: 2,
		vatBps: 2,
		stampDutyBps: 1,
		ibCommissionBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 1,
		fractionalSupported: 0
	},
	{
		exchange: 'CSE',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'AED',
		session: 'Regular',
		buyOrderValueQty: 'Quantity',
		brokerCommissionBps: 1,
		minFeePerTrade: 10,
		safeCustodyFees: 10,
		fixedAmountPerTrade: 10,
		transactionFeeBps: 2,
		vatBps: 2,
		stampDutyBps: 1,
		ibCommissionBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 1,
		fractionalSupported: 0
	}
];

export const MOCK_EUROPE_US = [
	{
		exchange: 'LSE1',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: '0-40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 0,
		brokerCommissionTo: 1000,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 1,
		transactionFeeBps: 2,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	},
	{
		exchange: 'LSE1',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: '0-40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 1000,
		brokerCommissionTo: 10000000,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 1,
		transactionFeeBps: 2,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	},
	{
		exchange: 'LSE1',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: '0-40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 10000000,
		brokerCommissionTo: 10000000000,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 1,
		transactionFeeBps: 2,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	},
	{
		exchange: 'LSE1',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: 'Over 40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 0,
		brokerCommissionTo: 1000,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 1,
		transactionFeeBps: 2,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	},
	{
		exchange: 'LSE1',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: 'Over 40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 1000,
		brokerCommissionTo: 10000000,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 1,
		transactionFeeBps: 2,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	},
	{
		exchange: 'LSE1',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: 'Over 40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 10000000,
		brokerCommissionTo: 10000000000,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 1,
		transactionFeeBps: 2,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	},
	{
		exchange: 'LSE1',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: 'Over 40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 10000,
		brokerCommissionTo: 999999999,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 2,
		transactionFeeBps: 4,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	},
	{
		exchange: 'LSE2',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: '0-40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 0,
		brokerCommissionTo: 1000,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 1,
		transactionFeeBps: 2,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	},
	{
		exchange: 'LSE2',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: '0-40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 1000,
		brokerCommissionTo: 10000000,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 1,
		transactionFeeBps: 2,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	},
	{
		exchange: 'LSE2',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: '0-40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 10000000,
		brokerCommissionTo: 10000000000,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 1,
		transactionFeeBps: 2,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	},
	{
		exchange: 'LSE2',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: 'Over 40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 0,
		brokerCommissionTo: 1000,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 1,
		transactionFeeBps: 2,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	},
	{
		exchange: 'LSE2',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: 'Over 40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 1000,
		brokerCommissionTo: 10000000,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 1,
		transactionFeeBps: 2,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	},
	{
		exchange: 'LSE2',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: 'Over 40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 10000000,
		brokerCommissionTo: 10000000000,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 1,
		transactionFeeBps: 2,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	},
	{
		exchange: 'LSE2',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'GBP',
		session: 'Regular',
		tieredQty: 'Over 40M',
		buyOrderValueQty: 'Value',
		brokerCommissionFrom: 10000,
		brokerCommissionTo: 999999999,
		brokerCommissionBps: 1,
		minFeePerTrade: 20,
		safeCustodyFees: 1,
		fixedAmountPerTrade: 2,
		transactionFeeBps: 4,
		vatBps: 3,
		stampDutyBps: 1,
		ptmLevyBps: 1,
		regulatoryFees: 1,
		settlementFeePerIsin: 10,
		fractionalSupported: 1
	}
];

export const MOCK_OPTION = [
	{
		exchange: 'DFM',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'AED',
		session: 'Regular',
		instrumentType: 'OPTION',
		buyOrderValueQty: 'Quantity',
		brokerCommissionBps: 1,
		minFeePerTrade: 10,
		safeCustodyFees: 10,
		fixedAmountPerTrade: 10,
		transactionFeeBps: 2,
		vatBps: 2,
		stampDutyBps: 1,
		ibCommissionBps: 1,
		settlementFeePerIsin: 1,
		fractionalSupported: 0
	}
];

export const MOCK_CFD = [
	{
		exchange: 'DFM',
		marketCode: 'ALL',
		marketId: 'ALL',
		subMarket: 'ALL',
		currency: 'AED',
		session: 'Regular',
		buyOrderValueQty: 'Value',
		brokerCommissionBps: 1,
		minFeePerTrade: 10,
		safeCustodyFees: 10,
		fixedAmountPerTrade: 10,
		transactionFeeBps: 2,
		vatBps: 2,
		stampDutyBps: 1,
		ibCommissionBps: 1,
		settlementFeePerIsin: 1,
		fractionalSupported: 0
	}
];

export default {
	Query: () => ( {
		getPriceSheetTemplateEquityMena: () => MOCK_MENA,
		getPriceSheetTemplateEquityAsia: () => MOCK_ASIA,
		getPriceSheetTemplateEquityEuropeUs: () => MOCK_EUROPE_US,
		getPriceSheetTemplateOption: () => MOCK_OPTION,
		getPriceSheetTemplateCFD: () => MOCK_CFD
	} ),
	Mutation: () => ( {
		updatePriceSheetTemplateEquityMena: () => true,
		updatePriceSheetTemplateEquityAsia: () => true,
		updatePriceSheetTemplateEquityEuropeUs: () => true,
		updatePriceSheetTemplateOption: () => true,
		updatePriceSheetTemplateCFD: () => true,
		upsertPriceSheetData: () => true
	} )
};
